services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # unified Dockerfile
    container_name: portfolio-backend
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
    volumes:
      - ./portfolio_backend/staticfiles:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
