version: '3.8'

services:
  backend:
    build: ./portfolio_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key
    volumes:
      - ./portfolio_backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    
  frontend:
    build: ./portfolio_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    volumes:
      - ./portfolio_frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend